---
- hosts: all
  tasks:
    - name: ensure docker is installed
      yum:
        name: docker
        state: installed

    - name: python-pip required to install pip
      yum:
        name: python-pip
        state: installed

    - name: docker-py required for docker containers
      pip:
        name: docker-py

    - name: ensure docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: ensure apache is running
      docker_container:
        name: myapplication
        image: httpd
        state: started
        restart: yes
        ports:
          - "80"
        env:
          SECRET_KEY: "ssssh"
          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
          BOOLEAN_KEY: "yes"
