---
- hosts: all
  remote_user: root
  tasks:
  - name: gcc and debuginfo rpms
    yum:
      name:
        - gcc
        - gdb
        - epel-release
        - lsof
        - ltrace
        - python3-pip
      state: present

  - name: asciinema playback
    shell: pip3 install asciinema

  - name: debuginfo install
    shell: debuginfo-install -y glibc-common bzip2-libs elfutils-libelf elfutils-libs libattr libcap libgcc systemd-libs xz-libs zlib || exit 0

  - name: bashrc updates
    copy:
      content: "export PATH=$PATH:/usr/local/bin\nalias ar='asciinema rec'\nalias ap='asciinema play'"
      dest: /etc/profile.d/getip.sh
  - name: hosts entry for getip_hostname
    lineinfile:
      dest: /etc/hosts
      line: "1.1.1.1     getip_hostname"
      state: present
