---
- hosts: all
  remote_user: root
  tasks:
  - name: gcc and debuginfo rpms
    yum:
      name:
        - gcc
        - gdb
        - epel-release
        - lsof
        - ltrace
        - python3-pip
        - strace
        - tmux
      state: present

  - name: asciinema playback
    shell: pip3 install asciinema

  - name: debuginfo install
    shell: debuginfo-install -y glibc-common bzip2-libs elfutils-libelf elfutils-libs libattr libcap libgcc systemd-libs xz-libs zlib || exit 0

  - name: bashrc updates
    copy:
      src:  ./getip.sh
      dest: /etc/profile.d/getip.sh
  - name: set limits on user foo
    copy:
      src: ./30-foo.conf
      dest: /etc/security/limits.d/30-foo.conf
  - name: hosts entry for getip_hostname
    lineinfile:
      dest: /etc/hosts
      line: "1.1.1.1     getip_hostname"
      state: present
  - name: foo group
    group:
      name: foo

  - name: foo user (limits demo)
    user:
      name: foo
      comment: Foo Bar
      uid: 1040
      group: foo
