---
- hosts: all
  remote_user: root
  tasks:
  - name: gcc and debuginfo rpms
    yum:
      name:
        - gdb
        - ltrace
      state: present
  - name: debuginfo install
    shell: debuginfo-install -y glibc-common bzip2-libs elfutils-libelf elfutils-libs libattr libcap libgcc systemd-libs xz-libs zlib
